module.exports = {
    aar: {code:'aar', name:'Afar'},
    abk: {code:'abk', name:'Abkhazian'},
    ace: {code:'ace', name:'Achinese'},
    ach: {code:'ach', name:'Acoli'},
    ada: {code:'ada', name:'Adangme'},
    ady: {code:'ady', name:'Adyghe; Adygei'},
    afa: {code:'afa', name:'Afro-Asiatic languages'},
    afh: {code:'afh', name:'Afrihili'},
    afr: {code:'afr', name:'Afrikaans'},
    ain: {code:'ain', name:'Ainu'},
    aka: {code:'aka', name:'Akan'},
    akk: {code:'akk', name:'Akkadian'},
    ale: {code:'ale', name:'Aleut'},
    alg: {code:'alg', name:'Algonquian languages'},
    alt: {code:'alt', name:'Southern Altai'},
    amh: {code:'amh', name:'Amharic'},
    ang: {code:'ang', name:'English, Old (ca.450–1100)'},
    anp: {code:'anp', name:'Angika'},
    apa: {code:'apa', name:'Apache languages'},
    ara: {code:'ara', name:'Arabic'},
    arc: {code:'arc', name:'Official Aramaic (700–300 BCE); Imperial Aramaic (700–300 BCE)'},
    arg: {code:'arg', name:'Aragonese'},
    arn: {code:'arn', name:'Mapudungun; Mapuche'},
    arp: {code:'arp', name:'Arapaho'},
    art: {code:'art', name:'Artificial languages'},
    arw: {code:'arw', name:'Arawak'},
    asm: {code:'asm', name:'Assamese'},
    ast: {code:'ast', name:'Asturian; Bable; Leonese; Asturleonese'},
    ath: {code:'ath', name:'Athapascan languages'},
    aus: {code:'aus', name:'Australian languages'},
    ava: {code:'ava', name:'Avaric'},
    ave: {code:'ave', name:'Avestan'},
    awa: {code:'awa', name:'Awadhi'},
    aym: {code:'aym', name:'Aymara'},
    aze: {code:'aze', name:'Azerbaijani'},
    bad: {code:'bad', name:'Banda languages'},
    bai: {code:'bai', name:'Bamileke languages'},
    bak: {code:'bak', name:'Bashkir'},
    bal: {code:'bal', name:'Baluchi'},
    bam: {code:'bam', name:'Bambara'},
    ban: {code:'ban', name:'Balinese'},
    bas: {code:'bas', name:'Basa'},
    bat: {code:'bat', name:'Baltic languages'},
    bej: {code:'bej', name:'Beja; Bedawiyet'},
    bel: {code:'bel', name:'Belarusian'},
    bem: {code:'bem', name:'Bemba'},
    ben: {code:'ben', name:'Bengali'},
    ber: {code:'ber', name:'Berber languages'},
    bho: {code:'bho', name:'Bhojpuri'},
    bih: {code:'bih', name:'Bihari languages'},
    bik: {code:'bik', name:'Bikol'},
    bin: {code:'bin', name:'Bini; Edo'},
    bis: {code:'bis', name:'Bislama'},
    bla: {code:'bla', name:'Siksika'},
    bnt: {code:'bnt', name:'Bantu languages'},
    bod: {code:'bod', name:'Tibetan'},
    bos: {code:'bos', name:'Bosnian'},
    bra: {code:'bra', name:'Braj'},
    bre: {code:'bre', name:'Breton'},
    btk: {code:'btk', name:'Batak languages'},
    bua: {code:'bua', name:'Buriat'},
    bug: {code:'bug', name:'Buginese'},
    bul: {code:'bul', name:'Bulgarian'},
    byn: {code:'byn', name:'Blin; Bilin'},
    cad: {code:'cad', name:'Caddo'},
    cai: {code:'cai', name:'Central American Indian languages'},
    car: {code:'car', name:'Galibi Carib'},
    cat: {code:'cat', name:'Catalan; Valencian'},
    cau: {code:'cau', name:'Caucasian languages'},
    ceb: {code:'ceb', name:'Cebuano'},
    cel: {code:'cel', name:'Celtic languages'},
    ces: {code:'ces', name:'Czech'},
    cha: {code:'cha', name:'Chamorro'},
    chb: {code:'chb', name:'Chibcha'},
    che: {code:'che', name:'Chechen'},
    chg: {code:'chg', name:'Chagatai'},
    chk: {code:'chk', name:'Chuukese'},
    chm: {code:'chm', name:'Mari'},
    chn: {code:'chn', name:'Chinook jargon'},
    cho: {code:'cho', name:'Choctaw'},
    chp: {code:'chp', name:'Chipewyan; Dene Suline'},
    chr: {code:'chr', name:'Cherokee'},
    chu: {code:'chu', name:'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'},
    chv: {code:'chv', name:'Chuvash'},
    chy: {code:'chy', name:'Cheyenne'},
    cmc: {code:'cmc', name:'Chamic languages'},
    cnr: {code:'cnr', name:'Montenegrin'},
    cop: {code:'cop', name:'Coptic'},
    cor: {code:'cor', name:'Cornish'},
    cos: {code:'cos', name:'Corsican'},
    cpe: {code:'cpe', name:'Creoles and pidgins, English based'},
    cpf: {code:'cpf', name:'Creoles and pidgins, French-based'},
    cpp: {code:'cpp', name:'Creoles and pidgins, Portuguese-based'},
    cre: {code:'cre', name:'Cree'},
    crh: {code:'crh', name:'Crimean Tatar; Crimean Turkish'},
    crp: {code:'crp', name:'Creoles and pidgins'},
    csb: {code:'csb', name:'Kashubian'},
    cus: {code:'cus', name:'Cushitic languages'},
    cym: {code:'cym', name:'Welsh'},
    dak: {code:'dak', name:'Dakota'},
    dan: {code:'dan', name:'Danish'},
    dar: {code:'dar', name:'Dargwa'},
    day: {code:'day', name:'Land Dayak languages'},
    del: {code:'del', name:'Delaware'},
    den: {code:'den', name:'Slave (Athapascan)'},
    dgr: {code:'dgr', name:'Dogrib'},
    din: {code:'din', name:'Dinka'},
    div: {code:'div', name:'Divehi; Dhivehi; Maldivian'},
    doi: {code:'doi', name:'Dogri'},
    dra: {code:'dra', name:'Dravidian languages'},
    dsb: {code:'dsb', name:'Lower Sorbian'},
    dua: {code:'dua', name:'Duala'},
    dyu: {code:'dyu', name:'Dyula'},
    dzo: {code:'dzo', name:'Dzongkha'},
    efi: {code:'efi', name:'Efik'},
    egy: {code:'egy', name:'Egyptian (Ancient)'},
    eka: {code:'eka', name:'Ekajuk'},
    ell: {code:'ell', name:'Greek'},
    elx: {code:'elx', name:'Elamite'},
    eng: {code:'eng', name:'English'},
    epo: {code:'epo', name:'Esperanto'},
    est: {code:'est', name:'Estonian'},
    eus: {code:'eus', name:'Basque'},
    ewe: {code:'ewe', name:'Ewe'},
    ewo: {code:'ewo', name:'Ewondo'},
    fan: {code:'fan', name:'Fang'},
    fao: {code:'fao', name:'Faroese'},
    faz: {code:'faz', name:'Persian'},
    fat: {code:'fat', name:'Fanti'},
    fij: {code:'fij', name:'Fijian'},
    fil: {code:'fil', name:'Filipino; Pilipino'},
    fin: {code:'fin', name:'Finnish'},
    fiu: {code:'fiu', name:'Finno-Ugrian languages'},
    fon: {code:'fon', name:'Fon'},
    fra: {code:'fra', name:'French'},
    frm: {code:'frm', name:'French, Middle (ca. 1400–1600)'},
    fro: {code:'fro', name:'French, Old (842–ca. 1400)'},
    frr: {code:'frr', name:'Northern Frisian'},
    frs: {code:'frs', name:'East Frisian Low Saxon'},
    fry: {code:'fry', name:'Western Frisian'},
    ful: {code:'ful', name:'Fulah'},
    fur: {code:'fur', name:'Friulian'},
    gaa: {code:'gaa', name:'Ga'},
    gay: {code:'gay', name:'Gayo'},
    gba: {code:'gba', name:'Gbaya'},
    gem: {code:'gem', name:'Germanic languages'},
    kat: {code:'kat', name:'Georgian'},
    deu: {code:'deu', name:'German'},
    gez: {code:'gez', name:'Geez'},
    gil: {code:'gil', name:'Gilbertese'},
    gla: {code:'gla', name:'Gaelic; Scottish Gaelic'},
    gle: {code:'gle', name:'Irish'},
    glg: {code:'glg', name:'Galician'},
    glv: {code:'glv', name:'Manx'},
    gmh: {code:'gmh', name:'German, Middle High (ca. 1050–1500)'},
    goh: {code:'goh', name:'German, Old High (ca. 750–1050)'},
    gon: {code:'gon', name:'Gondi'},
    gor: {code:'gor', name:'Gorontalo'},
    got: {code:'got', name:'Gothic'},
    grb: {code:'grb', name:'Grebo'},
    grc: {code:'grc', name:'Greek, Ancient (to 1453)'},
    grn: {code:'grn', name:'Guarani'},
    gsw: {code:'gsw', name:'Swiss German; Alemannic; Alsatian'},
    guj: {code:'guj', name:'Gujarati'},
    gwi: {code:'gwi', name:'Gwichin'},
    hai: {code:'hai', name:'Haida'},
    hat: {code:'hat', name:'Haitian; Haitian Creole'},
    hau: {code:'hau', name:'Hausa'},
    haw: {code:'haw', name:'Hawaiian'},
    heb: {code:'heb', name:'Hebrew'},
    her: {code:'her', name:'Herero'},
    hil: {code:'hil', name:'Hiligaynon'},
    him: {code:'him', name:'Himachali languages; Pahari languages'},
    hin: {code:'hin', name:'Hindi'},
    hit: {code:'hit', name:'Hittite'},
    hmn: {code:'hmn', name:'Hmong; Mong'},
    hmo: {code:'hmo', name:'Hiri Motu'},
    hrv: {code:'hrv', name:'Croatian'},
    hsb: {code:'hsb', name:'Upper Sorbian'},
    hun: {code:'hun', name:'Hungarian'},
    hup: {code:'hup', name:'Hupa'},
    hye: {code:'hye', name:'Armenian'},
    iba: {code:'iba', name:'Iban'},
    ibo: {code:'ibo', name:'Igbo'},
    ido: {code:'ido', name:'Ido'},
    iii: {code:'iii', name:'Sichuan Yi; Nuosu'},
    ijo: {code:'ijo', name:'Ijo languages'},
    iku: {code:'iku', name:'Inuktitut'},
    ile: {code:'ile', name:'Interlingue; Occidental'},
    ilo: {code:'ilo', name:'Iloko'},
    ina: {code:'ina', name:'Interlingua (International Auxiliary Language Association)'},
    inc: {code:'inc', name:'Indic languages'},
    ind: {code:'ind', name:'Indonesian'},
    ine: {code:'ine', name:'Indo-European languages'},
    inh: {code:'inh', name:'Ingush'},
    ipk: {code:'ipk', name:'Inupiaq'},
    ira: {code:'ira', name:'Iranian languages'},
    iro: {code:'iro', name:'Iroquoian languages'},
    isl: {code:'isl', name:'Icelandic'},
    ita: {code:'ita', name:'Italian'},
    jav: {code:'jav', name:'Javanese'},
    jbo: {code:'jbo', name:'Lojban'},
    jpn: {code:'jpn', name:'Japanese'},
    jpr: {code:'jpr', name:'Judeo-Persian'},
    jrb: {code:'jrb', name:'Judeo-Arabic'},
    kaa: {code:'kaa', name:'Kara-Kalpak'},
    kab: {code:'kab', name:'Kabyle'},
    kac: {code:'kac', name:'Kachin; Jingpho'},
    kal: {code:'kal', name:'Kalaallisut; Greenlandic'},
    kam: {code:'kam', name:'Kamba'},
    kan: {code:'kan', name:'Kannada'},
    kar: {code:'kar', name:'Karen languages'},
    kas: {code:'kas', name:'Kashmiri'},
    kau: {code:'kau', name:'Kanuri'},
    kaw: {code:'kaw', name:'Kawi'},
    kaz: {code:'kaz', name:'Kazakh'},
    kbd: {code:'kbd', name:'Kabardian'},
    kha: {code:'kha', name:'Khasi'},
    khi: {code:'khi', name:'Khoisan languages'},
    khm: {code:'khm', name:'Central Khmer'},
    kho: {code:'kho', name:'Khotanese; Sakan'},
    kik: {code:'kik', name:'Kikuyu; Gikuyu'},
    kin: {code:'kin', name:'Kinyarwanda'},
    kir: {code:'kir', name:'Kirghiz; Kyrgyz'},
    kmb: {code:'kmb', name:'Kimbundu'},
    kok: {code:'kok', name:'Konkani'},
    kom: {code:'kom', name:'Komi'},
    kon: {code:'kon', name:'Kongo'},
    kor: {code:'kor', name:'Korean'},
    kos: {code:'kos', name:'Kosraean'},
    kpe: {code:'kpe', name:'Kpelle'},
    krc: {code:'krc', name:'Karachay-Balkar'},
    krl: {code:'krl', name:'Karelian'},
    kro: {code:'kro', name:'Kru languages'},
    kru: {code:'kru', name:'Kurukh'},
    kua: {code:'kua', name:'Kuanyama; Kwanyama'},
    kum: {code:'kum', name:'Kumyk'},
    kur: {code:'kur', name:'Kurdish'},
    kut: {code:'kut', name:'Kutenai'},
    lad: {code:'lad', name:'Ladino'},
    lah: {code:'lah', name:'Lahnda'},
    lam: {code:'lam', name:'Lamba'},
    lao: {code:'lao', name:'Lao'},
    lat: {code:'lat', name:'Latin'},
    lav: {code:'lav', name:'Latvian'},
    lez: {code:'lez', name:'Lezghian'},
    lim: {code:'lim', name:'Limburgan; Limburger; Limburgish'},
    lin: {code:'lin', name:'Lingala'},
    lit: {code:'lit', name:'Lithuanian'},
    lol: {code:'lol', name:'Mongo'},
    loz: {code:'loz', name:'Lozi'},
    ltz: {code:'ltz', name:'Luxembourgish; Letzeburgesch'},
    lua: {code:'lua', name:'Luba-Lulua'},
    lub: {code:'lub', name:'Luba-Katanga'},
    lug: {code:'lug', name:'Ganda'},
    lui: {code:'lui', name:'Luiseno'},
    lun: {code:'lun', name:'Lunda'},
    luo: {code:'luo', name:'Luo (Kenya and Tanzania)'},
    lus: {code:'lus', name:'Lushai'},
    mad: {code:'mad', name:'Madurese'},
    mag: {code:'mag', name:'Magahi'},
    mah: {code:'mah', name:'Marshallese'},
    mai: {code:'mai', name:'Maithili'},
    mak: {code:'mak', name:'Makasar'},
    mal: {code:'mal', name:'Malayalam'},
    man: {code:'man', name:'Mandingo'},
    map: {code:'map', name:'Austronesian languages'},
    mar: {code:'mar', name:'Marathi'},
    mas: {code:'mas', name:'Masai'},
    mdf: {code:'mdf', name:'Moksha'},
    mdr: {code:'mdr', name:'Mandar'},
    men: {code:'men', name:'Mende'},
    mga: {code:'mga', name:'Irish, Middle (900–1200)'},
    mic: {code:'mic', name:'Mikmaq; Micmac'},
    min: {code:'min', name:'Minangkabau'},
    mis: {code:'mis', name:'Uncoded languages'},
    mkd: {code:'mkd', name:'Macedonian'},
    mkh: {code:'mkh', name:'Mon-Khmer languages'},
    mlg: {code:'mlg', name:'Malagasy'},
    mlt: {code:'mlt', name:'Maltese'},
    mnc: {code:'mnc', name:'Manchu'},
    mni: {code:'mni', name:'Manipuri'},
    mno: {code:'mno', name:'Manobo languages'},
    moh: {code:'moh', name:'Mohawk'},
    mon: {code:'mon', name:'Mongolian'},
    mos: {code:'mos', name:'Mossi'},
    mri: {code:'mri', name:'Maori'},
    msa : {code:'msa ', name:'Malay'},
    mul: {code:'mul', name:'Multiple languages'},
    mun: {code:'mun', name:'Munda languages'},
    mus: {code:'mus', name:'Creek'},
    mwl: {code:'mwl', name:'Mirandese'},
    mwr: {code:'mwr', name:'Marwari'},
    mya: {code:'mya', name:'Burmese'},
    myn: {code:'myn', name:'Mayan languages'},
    myv: {code:'myv', name:'Erzya'},
    nah: {code:'nah', name:'Nahuatl languages'},
    nai: {code:'nai', name:'North American Indian languages'},
    nap: {code:'nap', name:'Neapolitan'},
    nau: {code:'nau', name:'Nauru'},
    nav: {code:'nav', name:'Navajo; Navaho'},
    nbl: {code:'nbl', name:'Ndebele, South; South Ndebele'},
    nde: {code:'nde', name:'Ndebele, North; North Ndebele'},
    ndo: {code:'ndo', name:'Ndonga'},
    nds: {code:'nds', name:'Low German; Low Saxon; German, Low; Saxon, Low'},
    nep: {code:'nep', name:'Nepali'},
    new: {code:'new', name:'Nepal Bhasa; Newari'},
    nia: {code:'nia', name:'Nias'},
    nic: {code:'nic', name:'Niger-Kordofanian languages'},
    niu: {code:'niu', name:'Niuean'},
    nld: {code:'nld', name:'Dutch; Flemish'},
    nno: {code:'nno', name:'Norwegian Nynorsk; Nynorsk, Norwegian'},
    nob: {code:'nob', name:'Bokmål, Norwegian; Norwegian Bokmål'},
    nog: {code:'nog', name:'Nogai'},
    non: {code:'non', name:'Norse, Old'},
    nor: {code:'nor', name:'Norwegian'},
    nqo: {code:'nqo', name:'NKo'},
    nso: {code:'nso', name:'Pedi; Sepedi; Northern Sotho'},
    nub: {code:'nub', name:'Nubian languages'},
    nwc: {code:'nwc', name:'Classical Newari; Old Newari; Classical Nepal Bhasa'},
    nya: {code:'nya', name:'Chichewa; Chewa; Nyanja'},
    nym: {code:'nym', name:'Nyamwezi'},
    nyn: {code:'nyn', name:'Nyankole'},
    nyo: {code:'nyo', name:'Nyoro'},
    nzi: {code:'nzi', name:'Nzima'},
    oci: {code:'oci', name:'Occitan (post 1500)'},
    oji: {code:'oji', name:'Ojibwa'},
    ori: {code:'ori', name:'Oriya'},
    orm: {code:'orm', name:'Oromo'},
    osa: {code:'osa', name:'Osage'},
    oss: {code:'oss', name:'Ossetian; Ossetic'},
    ota: {code:'ota', name:'Turkish, Ottoman (1500–1928)'},
    oto: {code:'oto', name:'Otomian languages'},
    paa: {code:'paa', name:'Papuan languages'},
    pag: {code:'pag', name:'Pangasinan'},
    pal: {code:'pal', name:'Pahlavi'},
    pam: {code:'pam', name:'Pampanga; Kapampangan'},
    pan: {code:'pan', name:'Panjabi; Punjabi'},
    pap: {code:'pap', name:'Papiamento'},
    pau: {code:'pau', name:'Palauan'},
    peo: {code:'peo', name:'Persian, Old (ca. 600–400 B.C.)'},
    phi: {code:'phi', name:'Philippine languages'},
    phn: {code:'phn', name:'Phoenician'},
    pli: {code:'pli', name:'Pali'},
    pol: {code:'pol', name:'Polish'},
    pon: {code:'pon', name:'Pohnpeian'},
    por: {code:'por', name:'Portuguese'},
    pra: {code:'pra', name:'Prakrit languages'},
    pro: {code:'pro', name:'Provençal, Old (to 1500); Old Occitan (to 1500)'},
    pus: {code:'pus', name:'Pushto; Pashto'},
    que: {code:'que', name:'Quechua'},
    raj: {code:'raj', name:'Rajasthani'},
    rap: {code:'rap', name:'Rapanui'},
    rar: {code:'rar', name:'Rarotongan; Cook Islands Maori'},
    roa: {code:'roa', name:'Romance languages'},
    roh: {code:'roh', name:'Romansh'},
    rom: {code:'rom', name:'Romany'},
    ron: {code:'ron', name:'Romanian; Moldavian; Moldovan'},
    run: {code:'run', name:'Rundi'},
    rup: {code:'rup', name:'Aromanian; Arumanian; Macedo-Romanian'},
    rus: {code:'rus', name:'Russian'},
    sad: {code:'sad', name:'Sandawe'},
    sag: {code:'sag', name:'Sango'},
    sah: {code:'sah', name:'Yakut'},
    sai: {code:'sai', name:'South American Indian languages'},
    sal: {code:'sal', name:'Salishan languages'},
    sam: {code:'sam', name:'Samaritan Aramaic'},
    san: {code:'san', name:'Sanskrit'},
    sas: {code:'sas', name:'Sasak'},
    sat: {code:'sat', name:'Santali'},
    scn: {code:'scn', name:'Sicilian'},
    sco: {code:'sco', name:'Scots'},
    sel: {code:'sel', name:'Selkup'},
    sem: {code:'sem', name:'Semitic languages'},
    sga: {code:'sga', name:'Irish, Old (to 900)'},
    sgn: {code:'sgn', name:'Sign Languages'},
    shn: {code:'shn', name:'Shan'},
    sid: {code:'sid', name:'Sidamo'},
    sin: {code:'sin', name:'Sinhala; Sinhalese'},
    sio: {code:'sio', name:'Siouan languages'},
    sit: {code:'sit', name:'Sino-Tibetan languages'},
    sla: {code:'sla', name:'Slavic languages'},
    slk: {code:'slk', name:'Slovak'},
    slv: {code:'slv', name:'Slovenian'},
    sma: {code:'sma', name:'Southern Sami'},
    sme: {code:'sme', name:'Northern Sami'},
    smi: {code:'smi', name:'Sami languages'},
    smj: {code:'smj', name:'Lule Sami'},
    smn: {code:'smn', name:'Inari Sami'},
    smo: {code:'smo', name:'Samoan'},
    sms: {code:'sms', name:'Skolt Sami'},
    sna: {code:'sna', name:'Shona'},
    snd: {code:'snd', name:'Sindhi'},
    snk: {code:'snk', name:'Soninke'},
    sog: {code:'sog', name:'Sogdian'},
    som: {code:'som', name:'Somali'},
    son: {code:'son', name:'Songhai languages'},
    sot: {code:'sot', name:'Sotho, Southern'},
    spa: {code:'spa', name:'Spanish; Castilian'},
    sqi: {code:'sqi', name:'Albanian'},
    srd: {code:'srd', name:'Sardinian'},
    srn: {code:'srn', name:'Sranan Tongo'},
    srp: {code:'srp', name:'Serbian'},
    srr: {code:'srr', name:'Serer'},
    ssa: {code:'ssa', name:'Nilo-Saharan languages'},
    ssw: {code:'ssw', name:'Swati'},
    suk: {code:'suk', name:'Sukuma'},
    sun: {code:'sun', name:'Sundanese'},
    sus: {code:'sus', name:'Susu'},
    sux: {code:'sux', name:'Sumerian'},
    swa: {code:'swa', name:'Swahili'},
    swe: {code:'swe', name:'Swedish'},
    syc: {code:'syc', name:'Classical Syriac'},
    syr: {code:'syr', name:'Syriac'},
    tah: {code:'tah', name:'Tahitian'},
    tai: {code:'tai', name:'Tai languages'},
    tam: {code:'tam', name:'Tamil'},
    tat: {code:'tat', name:'Tatar'},
    tel: {code:'tel', name:'Telugu'},
    tem: {code:'tem', name:'Timne'},
    ter: {code:'ter', name:'Tereno'},
    tet: {code:'tet', name:'Tetum'},
    tgk: {code:'tgk', name:'Tajik'},
    tgl: {code:'tgl', name:'Tagalog'},
    tha: {code:'tha', name:'Thai'},
    tig: {code:'tig', name:'Tigre'},
    tir: {code:'tir', name:'Tigrinya'},
    tiv: {code:'tiv', name:'Tiv'},
    tkl: {code:'tkl', name:'Tokelau'},
    tlh: {code:'tlh', name:'Klingon; tlhIngan-Hol'},
    tli: {code:'tli', name:'Tlingit'},
    tmh: {code:'tmh', name:'Tamashek'},
    tog: {code:'tog', name:'Tonga (Nyasa)'},
    ton: {code:'ton', name:'Tonga (Tonga Islands)'},
    tpi: {code:'tpi', name:'Tok Pisin'},
    tsi: {code:'tsi', name:'Tsimshian'},
    tsn: {code:'tsn', name:'Tswana'},
    tso: {code:'tso', name:'Tsonga'},
    tuk: {code:'tuk', name:'Turkmen'},
    tum: {code:'tum', name:'Tumbuka'},
    tup: {code:'tup', name:'Tupi languages'},
    tur: {code:'tur', name:'Turkish'},
    tut: {code:'tut', name:'Altaic languages'},
    tvl: {code:'tvl', name:'Tuvalu'},
    twi: {code:'twi', name:'Twi'},
    tyv: {code:'tyv', name:'Tuvinian'},
    udm: {code:'udm', name:'Udmurt'},
    uga: {code:'uga', name:'Ugaritic'},
    uig: {code:'uig', name:'Uighur; Uyghur'},
    ukr: {code:'ukr', name:'Ukrainian'},
    umb: {code:'umb', name:'Umbundu'},
    und: {code:'und', name:'Undetermined'},
    urd: {code:'urd', name:'Urdu'},
    uzb: {code:'uzb', name:'Uzbek'},
    vai: {code:'vai', name:'Vai'},
    ven: {code:'ven', name:'Venda'},
    vie: {code:'vie', name:'Vietnamese'},
    vol: {code:'vol', name:'Volapük'},
    vot: {code:'vot', name:'Votic'},
    wak: {code:'wak', name:'Wakashan languages'},
    wal: {code:'wal', name:'Wolaitta; Wolaytta'},
    war: {code:'war', name:'Waray'},
    was: {code:'was', name:'Washo'},
    wen: {code:'wen', name:'Sorbian languages'},
    wln: {code:'wln', name:'Walloon'},
    wol: {code:'wol', name:'Wolof'},
    xal: {code:'xal', name:'Kalmyk; Oirat'},
    xho: {code:'xho', name:'Xhosa'},
    yao: {code:'yao', name:'Yao'},
    yap: {code:'yap', name:'Yapese'},
    yid: {code:'yid', name:'Yiddish'},
    yor: {code:'yor', name:'Yoruba'},
    ypk: {code:'ypk', name:'Yupik languages'},
    zap: {code:'zap', name:'Zapotec'},
    zbl: {code:'zbl', name:'Blissymbols; Blissymbolics; Bliss'},
    zen: {code:'zen', name:'Zenaga'},
    zgh: {code:'zgh', name:'Standard Moroccan Tamazight'},
    zha: {code:'zha', name:'Zhuang; Chuang'},
    zho: {code:'zho', name:'Chinese'},
    znd: {code:'znd', name:'Zande languages'},
    zul: {code:'zul', name:'Zulu'},
    zun: {code:'zun', name:'Zuni'},
    zxx: {code:'zxx', name:'No linguistic content; Not applicable'},
    zza: {code:'zza', name:'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'},
    chi: {code:'chi', name:'Chinese'},
    alb: {code:'alb', name:'Albanian'},
    tib: {code:'tib', name:'Tibetan'},
    slo: {code:'slo', name:'Slovak'},
    rum: {code:'rum', name:'Romanian; Moldavian; Moldovan'},
    dut: {code:'dut', name:'Dutch; Flemish'},
    cze: {code:'cze', name:'Czech'},
    wel: {code:'wel', name:'Welsh'},
    gre: {code:'gre', name:'Greek'},
    baq: {code:'baq', name:'Basque'},
    per: {code:'per', name:'Persian'},
    fre: {code:'fre', name:'French'},
    geo: {code:'geo', name:'Georgian'},
    ger: {code:'ger', name:'German'},
    arm: {code:'arm', name:'Armenian'},
    ice: {code:'ice', name:'Icelandic'},
    mac: {code:'mac', name:'Macedonian'},
    mao: {code:'mao', name:'Maori'},
    may: {code:'may', name:'Malay'},
    bur: {code:'bur', name:'Burmese'},
    
};